set -U fish_greeting "Welcome to Aartools! For help, see https://elfhosted.com/app/arrtools/"
alias backup-sonarr="cd /config; cp confighd.ini config.ini; python /app/backup_sonarr_2csv.py"
alias backup-sonarr4k="cd /config; cp config4k.ini config.ini; python /app/backup_sonarr_2csv.py"
alias backup-radarr="cd /config; cp confighd.ini config.ini; python /app/backup_radarr_2csv.py"
alias backup-radarr4k="cd /config; cp config4k.ini config.ini; python /app/backup_radarr_2csv.py"