#!/usr/bin/with-contenv sh

echo "[$(basename "$(pwd)")] starting..."

/usr/bin/rclone rcd \
    --rc-web-gui \
    --rc-addr=0.0.0.0:5572 \
    --rc-web-gui-no-open-browser \
    --rc-no-auth \
    --transfers=1 \
    --bwlimit=10M \
    --multi-thread-streams=1