#!/command/with-contenv sh

s6-setuidgid ${PUID}:${PGID} \
/usr/bin/rclone serve webdav \
    --config=/config/rclone.conf \
    --addr :5574 \
    --user ${WEBDAV_USERNAME} \
    --pass ${WEBDAV_PASSWORD} \
    --transfers=1 \
    --bwlimit=10M \
    --multi-thread-streams=1 \
    --no-modtime \
    --vfs-read-chunk-size=10M \
    --vfs-read-chunk-size-limit=10M \
    --max-header-bytes=8192 \
    --stats 60s \
    -v \
    /storage