#!/command/with-contenv sh

s6-setuidgid ${PUID}:${PGID} \
/usr/bin/rclone serve webdav \
    --config=/config/rclone.conf \
    --addr :5574 \
    --user ${WEBDAV_USERNAME} \
    --pass ${WEBDAV_PASSWORD} \
    /storage