#!/command/with-contenv sh

s6-setuidgid ${PUID}:${PGID} \
/usr/bin/rclone rcd \
    --config=/config/rclone.conf \
    --rc-web-gui \
    --rc-addr=0.0.0.0:5572 \
    --rc-web-gui-no-open-browser \
    --rc-no-auth \
    /var/lib/rcloneui

    # --transfers=1 \
    # --bwlimit=10M \
    # --multi-thread-streams=1 \