#!/bin/bash

if [[ $# -lt 2 ]]; then 
    echo "usage: elfbot <command> <app> <optional>"
    echo
    echo app name must match an app found in /config
    echo "command options:"
    echo "restart : restarts an app"
    echo "reset <yesiamsure>: resets an app to defaults"
    echo "backup <path>: creates a dated backup in <path>"
    echo "claim <token>: claims a plex server"
fi

if [[ ! -d "/storage/config/$2" ]]; then
    echo "/config/$2 does not exist. Cannot continue"
    exit 1
fi

case $1 in

    "restart")
        echo "restarting $2..."
        touch /storage/config/$2/elfbot-restart
        ;;

    "reset")
        if [[ ! "$3" -eq "yesiamsure" ]]; then
            echo potentially dangerous! add 'yesiamsure' after your reset command to force
            exit 1
        fi      
        echo "resetting $2..."
        touch /storage/config/$2/elfbot-reset
        ;;

    "backup")
        echo "backing up $2 to $3..."
        TIMESTAMP=$(printf '%(%Y-%m-%d--%H-%M-%S)T\n' -1)
        echo $3/$2 > /storage/config/$2/elfbot-backup && \
        echo "restarting, backup will be saved as $3/$2-$TIMESTAMP ...
        ;;       

    "claim")
        if [[ "$2" == "plex" ]]; then
            echo "attempting plex claim with token [$3]..."
            /usr/local/bin/claim-plex-server.sh $3
        else
            echo "this command is only for claiming plex"
        fi
        ;;         

esac


