#!/command/with-contenv bash

# Run the mounts.sh script with a 2-second timeout
if ! timeout 2s /scripts/mounts.sh; then
  echo "[mounts-check] mounts.sh failed or timed out. Restarting plex service..."
  s6-svc -r /var/run/s6/services/plex
fi

# Run the wait-for-urls.sh script with a 2-second timeout
if ! timeout 2s /scripts/wait-for-urls.sh; then
  echo "[wait-for-urls-check] wait-for-urls.sh failed or timed out. Restarting plex service..."
  s6-svc -r /var/run/s6/services/plex
fi
